apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline
spec:
  params:
    - name: package
      type: string
      default: https://github.com/chabeezy/tekton-demo-nodejs
  workspaces:
    - name: workarea
      description: The workspace where the repo will be cloned
  results:
    - name: commit-sha
      description: the sha of the commit that was used
      value: $(tasks.clone.results.commit)
  tasks:
    - name: clone
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: workarea
          subpath: git
      params:
        - name: url
          value: https://$(params.package)
    - name: build
      runAfter: [clone]
      taskRef:
        name: node-build
      params:
        - name: package
          value: $(params.package)
      workspaces:
        - name: source
          workspace: workarea
          subpath: git
    - name: test-and-lint
      runAfter: [build]
      taskRef:
        name: node-test-and-lint
      params:
        - name: package
          value: $(params.package)
      workspaces:
        - name: source
          workspace: workarea
          subpath: git
    - name: run
      runAfter: [test-and-lint]
      taskRef:
        name: node-run
      params:
        - name: package
          value: $(params.package)
      workspaces:
        - name: source
          workspace: workarea
          subpath: git
