apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: node-run
spec:
  params:
    - name: package
      description: package (and its children) to run
    - name: context
      description: path to the directory to use as context
      default: "."
  steps:
    - image: node:17-alpine3.12
      name: 'run-the-app'
      script: |
        node index.js
      workingDir: $(workspaces.source.path)/$(params.context)
  workspaces:
    - name: source
